version: '3.3'

services:

  jee_REPLACE_PROJECT_NAME:
    image: REPLACE_IMAGE_NAME
    networks:
      - traefik_proxy
    environment:
       TZ: America/Montevideo
       DB_HOST: 
       DB_NAME: REPLACE_PROJECT_NAME
       DB_USER: 
       DB_PASS: 
       LOGSTASH_HOST:
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.backend=jee_REPLACE_PROJECT_NAME"
        - "traefik.frontend.rule=Host:REPLACE_URL_PROD"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.backend.loadbalancer.sticky=true"
        - "traefik.frontend.passHostHeader=true"
      restart_policy:
        condition: on-failure
 
networks:
  traefik_proxy:
    external: true
